### ISSUE TITLE
Click-ouside to hide FancySelect

### ISSUE THREAD

**Issue by lorenzos** [lorenzos/FancySelect#2]
Implement a click-outside event (using events on body) to hide FancySelect dropdown menus.

**Comment by lorenzos** [comment]
Done @bb0d36a4dd

**Comment by q88qaz** [comment]
whta's the method to hide FancySelect dropdown menus?

**Comment by lorenzos** [comment]
You can hide automatically using `autoHide` option:

```
var myFancySelect = new FancySelect(yourSelectElement, {
    autoHide: true
});
```

Or manually with `hide()`:

```
myFancySelect.hide();
```
