### ISSUE TITLE
Problem with legacyEvents

### ISSUE THREAD

**Issue by felixpfeiffer** [lorenzos/FancySelect#4]
Hello Lorenzo,

I just tried to use the script on a page, but need the fancyselect to fire the onchange event of the original select menue. I set legacyEvents true, but the onchange is not fired.

Here is the sourcecode of the original select:

```
<select name="filter[color]" id="ctrl_filter_color_79" class="select fancyselect" onchange="$('myform').submit();">
               <option value="">Farbe wählen</option>
               <option value="beige/creme">beige/creme</option>
               [...]
               <option value="weitere">weitere</option>
</select>
```

Do you have any hints, how I can fix this?

Thanx,
Felix

**Comment by lorenzos** [comment]
You should not use the `onchange` element attribute, but instead the Mootools Element event system (that is the one for which `legacyEvents` option was added).

So, remove the `onchange` attribute from the select and add this Javascript code instead:

```
// Probably you already wrapped your code in domready
document.addEvent('domready', function() {

    // This is the code you really need
    $('ctrl_filter_color_79').addEvent('change', function() {
        $('myform').submit();
    });

});
```

**Comment by felixpfeiffer** [comment]
Works great, thank you for the advise.

Felix
