### ISSUE TITLE
multiple opened selects are possible.

### ISSUE THREAD

**Issue by alxpolyakov** [lorenzos/FancySelect#5]
on autoHide=true select hides on mouse click. I offer something like this:

```
    // Auto-hide the dropdown menu on mouse leave
    if (this.options.autoHide) {
        this.ul.addEvent('mouseleave', function(e){
            if (!this.shown) return;
            this.hide();
        }.bind(this));
        this.div.addEvent('mouseleave', function(e){
            if (!this.shown) return;
            this.hide();
        }.bind(this));
    }
```

**Comment by lorenzos** [comment]
I disagree on your your solution: "normal" selects (I mean, the ones rendered by default by browser) does not disappear on mouse leave (it should be very unhandy!), but only when I click outside them.

Anyway I don't understand the problem, about multiple opened selects. If you use `autoHide: true`, selects are correctly "closed" when you click another one: you can't open many of them.
