### ISSUE TITLE
Don't work on mobile device

### ISSUE THREAD

**Issue by Desving** [lorenzos/FancySelect#7]
Hi. This plugin don't work in smartphone. If i open select in smartphone then text in select empty. In desctop it is work.

smartphone:
http://i.prntscr.com/f1pkcrp0RuutbC118eEqUw.png
http://i.prntscr.com/S68pl9gxT2muk4HZYb93AQ.png

Decstop:
http://i.prntscr.com/UXaSarhmRjypqgyF3jkVLw.png

**Comment by lorenzos** [comment]
Hi. I just tested the [demo page](http://www.lorenzostanco.com/lab/demos/FancySelect/Demo.html), and it works correctly on Android, both in Chrome and Firefox. Are you sure there aren't errors in your code somewhere else? What browser and device are you using? If the problem persists, try to send me a link where you try to isolate just that issue, so I can investigate it myself on live code.

**Comment by Desving** [comment]
Hi!
I am create demo page. https://desving.github.io/selectTest/

The problem can be repeated on the desktop if you turn on developer mode and reduce the screen to 320px and refresh the page. The same problem is present on all browsers in the mobile phone.

**Comment by lorenzos** [comment]
@Desving Hi! It looks like we have a case of homonymous libraries :smile: You are using **[FancySelect for jQuery](https://github.com/paulstraw/FancySelect)**, this is a different library developed earlier for Mootools.
